# Étape 1: Utiliser une image Node.js de base pour la construction de l'application React
FROM node:16 AS build

# Étape 2: Créer et définir le répertoire de travail
WORKDIR /app

# Étape 3: Copier les fichiers package.json et package-lock.json pour installer les dépendances
COPY package*.json ./

# Étape 4: Installer les dépendances nécessaires
RUN npm install

# Étape 5: Copier le reste du code de l'application React dans le conteneur
COPY . .

# Étape 6: Construire l'application React pour la production
RUN npm run build

# Étape 7: Utiliser une image Nginx pour servir l'application React en production
FROM nginx:alpine

# Étape 8: Copier les fichiers de construction dans le répertoire de Nginx
COPY --from=build /app/build /usr/share/nginx/html

# Étape 9: Exposer le port 80 pour Nginx
EXPOSE 3000

# Étape 10: Lancer Nginx pour servir l'application React
CMD ["nginx", "-g", "daemon off;"]
