version: "3.8"

services:

  frontend:
    image: rbenfraj46/front_react_shop:latest
    environment:
      - REACT_APP_VERSION=2.0
      - REACT_APP_API_URL=http://gateway:3001  
    ports:
      - "3000:80"
    networks:
      - app-network  


  gateway:
    image: rbenfraj46/gateway:latest
    environment:
      - PORT=3001
      - USER_SERVICE_URL=http://categoriems:3002  
      - PRODUIT_SERVICE_URL=http://productms:3003  
    depends_on:
      - categoriems  
      - productms  
      - mongodb  
    ports:
      - "3001:3001"
    networks:
      - app-network  


  categoriems:
    image: rbenfraj46/ms_category:latest
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - FRONTEND_URL=http://frontend:3000  
      - MONGO_URI=mongodb://mongodb:27017/categoridb 
    depends_on:
      - mongodb  
    ports:
      - "3002:3002"
    networks:
      - app-network  

  # Product Microservice (Flask)
  productms:
    image: rbenfraj46/ms_produit:latest
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - FRONTEND_URL=http://frontend:3000  
      - MONGO_URI=mongodb://mongodb:27017/produitdb  
    depends_on:
      - mongodb  
    ports:
      - "3003:3003"
    networks:
      - app-network 

  # MongoDB service
  mongodb:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db 
    ports:
      - "27017:27017"
    networks:
      - app-network  

networks:
  app-network:  
    driver: bridge  

volumes:
  mongo-data: 
